### PR TITLE
Tweaks & Fixes

### LINKED ISSUE #149: Internal server error when an order is placed
I tried placing an order and I got an internal server error:

image

Below are the logs:

[04-Apr-2022 17:44:47 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WSAL_Sensors_WooCommerce_Public::get_product_sku() in /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php:360
Stack trace:
#0 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-includes/class-wp-hook.php(307): WSAL_Sensors_WooCommerce_Public->product_stock_changed()
#1 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-includes/plugin.php(474): WP_Hook->do_action()
#3 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/woocommerce/includes/wc-stock-functions.php(63): do_action()
#4 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/woocommerce/includes/wc-stock-functions.php(189): wc_update_pr in /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php on line 360

### PR DESCRIPTION
**Pull request by DannyWPWS**
Fixes #149 etc

### CODE REVIEW

File: wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php [hunk 1]
```diff
@@ -388,4 +388,17 @@ private function get_stock_status( $slug ) {
 			return __( 'On backorder', 'wp-security-audit-log' );
```
Comment (martinkrcho) [inline wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php:388]:
```suggestion
			return esc_html__( 'On backorder', 'wp-security-audit-log' );
```

File: wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php [hunk 2]
```diff
@@ -388,4 +388,17 @@ private function get_stock_status( $slug ) {
...
 		}
 	}
+
+    /**
```
Comment (martinkrcho) [inline wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php:392]: Replace spaces with tabs, please.

File: wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php [hunk 3]
```diff
@@ -388,4 +388,17 @@ private function get_stock_status( $slug ) {
...
+	 * Get a SKU for a given product ID.
+	 *
+	 * @param  int $product_id - Id to lookup.
+	 *
+	 * @return int|string - Result.
+	 */
+	private function get_product_sku( $product_id ) {
+		$product = wc_get_product( $product_id );
+		$sku     = $product->get_sku();
+		return ( $sku ) ? $sku : __( 'Not provided', 'wsal-woocommerce' );
```
Comment (martinkrcho) [inline wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php:402]:
```suggestion
		return ( $sku ) ? $sku : esc_html__( 'Not provided', 'wsal-woocommerce' );
```

**Review by martinkrcho — CHANGES_REQUESTED** [review]
Couple of small tweaks needed.

**Review by martinkrcho — APPROVED** [review]
All changes looking good now.
